<!DOCTYPE html>
<div id="page-content-wrapper">
    <div class="container-fluid">
        
        <center><h1><u>Liste des catégories</u></h1></center><br>
        
        <table class="table table-striped table-bordered">
            <tr>
                <td style="width:90%; border-right:none;">
                    <strong>Label</strong>
                </td>
                <td style="width:10%; border:none;"></td>
            </tr>
        </table>
        
        <?php foreach($this->resultat as $resultat) : ?>
        
            <table class="table table-striped table-bordered">
                <tr>
                    <td style="width:90%; border-right:none;">
                        <?php echo $resultat['label_category']; ?>
                    </td>
                    <td style="width:10%; border-left:none;">
                        <a class="btn btn-primary" href="<?php echo $this->url(array('controller' => 'category', 'action' => 'update', 'id' => $resultat['id_category']), null, true) ?>">
                            Modifier
                        </a>
                    </td>
                </tr>
            </table>

        <?php endforeach;  ?>
        
    </div>
</div>