
<div class="container">
    <br><br>
    <h1 class="header center orange-text">BackOffice Hi Tech Online</h1>
    <div class="row center">
        <h5 class="header col s12 light">Le site de gestion de vente privée en ligne</h5>
    </div>
    <div class="row center">
        <div class="row">
            <form class="col s12" method="POST" action="<?php echo $this->url(array('controller' => 'session', 'action' => 'connect'), null, true); ?>">
                <div class="row">
                    <div class="input-field col s6">
                        <input  type="text" name="identifiant" class="validate">
                        <label for="first_name">Identifiant</label>
                    </div>
                    <div class="input-field col s6">
                        <input type="password" name="password" class="validate">
                        <label for="last_name">Mot de passe</label>
                    </div>
                </div>

                <button class="btn waves-effect waves-light" type="submit" name="action">Se connecter
                    <i class="material-icons">send</i>
                </button>
            </form>
        </div>

    </div>
</div>
<!--  
<div class="valign-wrapper">
    <div class='valign' style="position:relative; padding-top:50px;">
        <div class="col s12 m10">
            <div class='row'>
              
                    <div class="card large" style='height:auto; padding-left: 5px; padding-right: 5px;'>


                        <div class="col s12 m4">
                            <div class="col s12">
                                <a href="revue/liste" style="margin:0!important;"> <div  class="card-panel teal center-align btn waves-effect waves-light formateCartouche"  >
                                        <span class="white-text" >LISTE DES ARTICLES </span>
                                    </div></a>
                            </div>
                            <div class="col s12">
                                <a href="revue/creation" style="margin:0!important; "> <div  class="card-panel teal center-align btn waves-effect waves-light formateCartouche"  >
                                        <span class="white-text"> CREER UN ARTICLE </span>
                                    </div></a>
                            </div>
                            <div class="col s12">
                                <a href="actualite/creer" style="margin:0!important; "> <div  class="card-panel teal center-align btn waves-effect waves-light formateCartouche"  >
                                        <span class="white-text">CREER UNE ACTUALITE  </span>
                                    </div></a>  
                            </div>
                        </div>


                        <div class="col s12 m4">
                            <div class="col s12">
                                <a href="breve/liste" style="margin:0!important; "> <div class="card-panel teal center-align btn waves-effect waves-light formateCartouche"  >
                                        <span class="white-text">LISTE DES EVENEMENTS </span>
                                    </div></a>
                            </div>
                            <div class="col s12">

                                <a href="breve/creer" style="margin:0!important; "> <div class="card-panel teal center-align btn waves-effect waves-light formateCartouche"  >
                                        <span class="white-text">CREER UN EVENEMENT </span>
                                    </div></a>
                            </div>
                            <div class="col s12">
                                <a href="recherche" style="margin:0!important; "> <div class="card-panel teal center-align btn waves-effect waves-light formateCartouche"  >
                                        <span class="white-text">FGFG </span>
                                    </div></a>
                            </div>

                        </div>


                        <div class="col s12 m4">
                            <div class="col s12">
                                <a href="actualite/liste" style="margin:0!important; "> <div class="card-panel teal center-align btn waves-effect waves-light formateCartouche"  >
                                        <span class="white-text">LISTE DES ACTUALITES </span>
                                    </div></a>
                            </div>
                            <div class="col s12">
                                <a href="compte" style="margin:0!important; "> <div class="card-panel teal center-align btn waves-effect waves-light formateCartouche"  >
                                        <span class="white-text">GESTION DE COMPTE</span>
                                    </div></a>
                            </div>


                            <div class="col s12">
                                <a href="article/liste" style="margin:0!important; "> <div class="card-panel teal center-align btn waves-effect waves-light formateCartouche"  >
                                        <span class="white-text">LISTE DES ARTICLES</span>
                                    </div></a>
                            </div>
                        </div>

                    </div>

                </div>
            </div>
      
    </div>
</div>  
<style>
    .formateCartouche{
        padding-top: 12px;
        width:100%!important; 
        height: auto;
        background-color: #5A62B9 !important;
    }
</style>-->
