<div style="margin-left:50px; margin-right:52%">
    <br/><h2><u>Contrôle de la vente</u></h2><br/>
    
    <?php echo $this->message; ?>
    
    <br/>
    <table class="table table-striped table-bordered">
        <tr>
            <td style="width:50%; border-right:none;">
                <strong>Image :</strong>
            </td>
            <td style="width:50%; border-right:none;">
                <img 
                    style = "width:300px; height:400px;" 
                    src = "data:image/<?php echo $this->name_image . ' ;base64,' . $this->image ?>" 
                />
            </td>
        </tr>
        <tr>
            <td style="width:50%; border-right:none;">
                <strong>Titre :</strong>
            </td>
            <td style="width:50%; border-right:none;">
                <?php echo $this->sell['title'] ?>
            </td>
        </tr>
        <tr>
            <td style="width:50%; border-right:none;">
                <strong>Description :</strong>
            </td>
            <td style="width:50%; border-right:none;">
                <?php echo $this->sell['description'] ?>
            </td>
        </tr>
        <tr>
            <td style="width:50%; border-right:none;">
                <strong>Prix :</strong>
            </td>
            <td style="width:50%; border-right:none;">
                <?php echo $this->sell['price'] . '€' ?>
            </td>
        </tr>
        <tr>
            <td style="width:50%; border-right:none;">
                <strong>Quantité :</strong>
            </td>
            <td style="width:50%; border-right:none;">
                <?php echo $this->sell['quantity'] ?>
            </td>
        </tr>
    </table>
    
    <br/>

    <?php echo $this->form; ?>
</div>