
<div class="row">
    <div class="col s12 m12 l12">
        <div class="card-panel">
            <h4 class="header2">Liste des évènements</h4>
            <div class="row">
                <div class="col s12">
             <div class="row">
                  <div class="col s12">
                    <ul style="width: 100%;" class="tabs tab-demo-active z-depth-1 cyan">
                      <li style="width: 45%;" class="disabled tab "><a class="white-text waves-effect waves " href="#sapien">Evènement</a>
                      </li>
                      <li style="width: 10%;" class="disabled tab  "><a class="white-text waves-effect waves " href="#">Ajouter</a>
                      </li>
                      <li style="width: 10%;" class="disabled tab  "><a class="white-text waves-effect waves" href="#activeone">Modifier</a>
                      </li>
                      <li style="width: 35%;" class="disabled tab "><a class="white-text waves-effect waves" href="#vestibulum">Supprimer </a>
                      </li>
                            </ul>
                  </div>
                  <div class="col s12">
                    <div style="display: block;" id="sapien" class="col s12 ">
                     <div class="row">
                                              <ul id="issues-collection" class="collection">
                                    
                                    <li class="collection-item">
                                        <div class="row">
                                            <div class="col s6">
                                                <p class="collections-title"><strong>#102</strong> Evenement d'été</p>
                                                <p class="collections-content">Voici la description</p>
                                                <p class="collections-title">du date 1 au date 2</p>
                                            </div>
                                            <div class="col s2">
                                               <a class="waves-effect waves-light btn"><i class="material-icons right"></i>Ajouter</a>
        
                                            </div>
                                            <div class="col s2">
                                               <a class="waves-effect waves-light btn"><i class="material-icons right"></i>Modifier</a>
        
                                            </div>
                                            <div class="col s2">
                                                <a class="waves-effect waves-light btn"><i class="material-icons right"></i>Supprimer</a>
                                                      
                                            </div>
                                        </div>
                                    </li>
                                   
                                    
                                    
                                </ul>
                                
                                            </div>

                    </div>
                    <div style="display: none;" id="activeone" class="col s12  cyan lighten-4">
                      <dl>
                        <dt>Definition list</dt>
                        <dd>Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</dd>
                        <dt>Lorem ipsum dolor sit amet</dt>
                        <dd>Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</dd>
                      </dl>
                    </div>
                    <div style="display: none;" id="vestibulum" class="col s12  cyan lighten-4">
                      <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies
                        mi vitae est. Mauris placerat eleifend leo.</p>
                    </div>
                  </div>
                </div>
              </div>
                </div>
        </div>
    </div>
</div>
</div>