<?php

//Base de données
define('DB_NAME_HI_TECH_ONLINE', 'hi_tech_online');

//Tables
define('DB_TABLE_ACTEUR', DB_NAME_HI_TECH_ONLINE . '.acteur');
define('DB_TABLE_CARACTERISTIQUE', DB_NAME_HI_TECH_ONLINE . '.caracteristique');
define('DB_TABLE_CATEGORIE', DB_NAME_HI_TECH_ONLINE . '.categorie');
define('DB_TABLE_CLIENT', DB_NAME_HI_TECH_ONLINE . '.client');
define('DB_TABLE_CLIENT_NEWSLETTER', DB_NAME_HI_TECH_ONLINE . '.client_newsletter');
define('DB_TABLE_COMMANDE', DB_NAME_HI_TECH_ONLINE . '.commande');
define('DB_TABLE_COMMANDE_LIVREUR', DB_NAME_HI_TECH_ONLINE . '.commande_livreur');
define('DB_TABLE_DETAIL', DB_NAME_HI_TECH_ONLINE . '.detail');
define('DB_TABLE_DETAIL_LIVREUR', DB_NAME_HI_TECH_ONLINE . '.detail_livreur');
define('DB_TABLE_EVENEMENT', DB_NAME_HI_TECH_ONLINE . '.evenement');
define('DB_TABLE_LIGNE_COMMANDE', DB_NAME_HI_TECH_ONLINE . '.ligne_commande');
define('DB_TABLE_LIVREUR', DB_NAME_HI_TECH_ONLINE . '.livreur');
define('DB_TABLE_NEWSLETTER', DB_NAME_HI_TECH_ONLINE . '.newsletter');
define('DB_TABLE_PRODUIT', DB_NAME_HI_TECH_ONLINE . '.produit');
define('DB_TABLE_PRODUIT_CARACTERISTIQUE', DB_NAME_HI_TECH_ONLINE . '.produit_caracteristique');
define('DB_TABLE_PRODUIT_EVENEMENT', DB_NAME_HI_TECH_ONLINE . '.produit_evenement');

